In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
#from collections import Counter
%matplotlib inline

import pyforest

import warnings
warnings.filterwarnings("ignore")

from sklearn import metrics
from sklearn.metrics import accuracy_score

In [2]:
lazy_imports()

['from sklearn.manifold import TSNE',
 'import tqdm',
 'from sklearn.model_selection import train_test_split',
 'import glob',
 'import plotly as py',
 'import pandas as pd',
 'from pyspark import SparkContext',
 'import bokeh',
 'from sklearn.ensemble import GradientBoostingClassifier',
 'import pickle',
 'import dash',
 'import keras',
 'from sklearn.ensemble import RandomForestClassifier',
 'import matplotlib.pyplot as plt',
 'from sklearn.ensemble import RandomForestRegressor',
 'import plotly.graph_objs as go',
 'import plotly.express as px',
 'from sklearn import svm',
 'import sys',
 'from sklearn.preprocessing import OneHotEncoder',
 'import os',
 'from sklearn.feature_extraction.text import TfidfVectorizer',
 'import re',
 'import statistics',
 'import matplotlib as mpl',
 'import numpy as np',
 'import spacy',
 'from dask import dataframe as dd',
 'import sklearn',
 'import nltk',
 'import xgboost as xgb',
 'import seaborn as sns',
 'from sklearn.ensemble import GradientBoost

In [31]:
X = pd.read_csv('TrainingDataset.csv', sep=';', skiprows=1, 
                names=['fixed acidity', 'volatile acidity','citric acid', 'residual sugar', 'chlorides','free sulfur dioxide' , 'total sulfur dioxide','density','pH', 'sulphates','alcohol','quality'])

In [32]:
X.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            8.9              0.22         0.48             1.8      0.077   
1            7.6              0.39         0.31             2.3      0.082   
2            7.9              0.43         0.21             1.6      0.106   
3            8.5              0.49         0.11             2.3      0.084   
4            6.9              0.40         0.14             2.4      0.085   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 29.0                  60.0   0.9968  3.39       0.53   
1                 23.0                  71.0   0.9982  3.52       0.65   
2                 10.0                  37.0   0.9966  3.17       0.91   
3                  9.0                  67.0   0.9968  3.17       0.53   
4                 21.0                  40.0   0.9968  3.43       0.63   

   alcohol  quality  
0      9.4        6  
1      9.7        5  
2      9.5        5  
3      9.4        5  
4      9.7        6

In [33]:
Y= pd.read_csv('TrainingDataset.csv', sep=';', skiprows=1, 
                names=['fixed acidity', 'volatile acidity','citric acid', 'residual sugar', 'chlorides','free sulfur dioxide' , 'total sulfur dioxide','density','pH', 'sulphates','alcohol','quality'])

In [34]:
Y.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            8.9              0.22         0.48             1.8      0.077   
1            7.6              0.39         0.31             2.3      0.082   
2            7.9              0.43         0.21             1.6      0.106   
3            8.5              0.49         0.11             2.3      0.084   
4            6.9              0.40         0.14             2.4      0.085   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 29.0                  60.0   0.9968  3.39       0.53   
1                 23.0                  71.0   0.9982  3.52       0.65   
2                 10.0                  37.0   0.9966  3.17       0.91   
3                  9.0                  67.0   0.9968  3.17       0.53   
4                 21.0                  40.0   0.9968  3.43       0.63   

   alcohol  quality  
0      9.4        6  
1      9.7        5  
2      9.5        5  
3      9.4        5  
4      9.7        6

In [35]:
X_train = X.iloc[:,0:11]

In [36]:
X_train.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            8.9              0.22         0.48             1.8      0.077   
1            7.6              0.39         0.31             2.3      0.082   
2            7.9              0.43         0.21             1.6      0.106   
3            8.5              0.49         0.11             2.3      0.084   
4            6.9              0.40         0.14             2.4      0.085   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 29.0                  60.0   0.9968  3.39       0.53   
1                 23.0                  71.0   0.9982  3.52       0.65   
2                 10.0                  37.0   0.9966  3.17       0.91   
3                  9.0                  67.0   0.9968  3.17       0.53   
4                 21.0                  40.0   0.9968  3.43       0.63   

   alcohol  
0      9.4  
1      9.7  
2      9.5  
3      9.4  
4      9.7

In [48]:
y_train = X.iloc[:,11]

In [51]:
y_train.head(5)

quality
0        6
1        5
2        5
3        5
4        6

In [50]:
y_train = pd.DataFrame(y_train)

In [52]:
X_test = Y.iloc[:,0:11]
y_test = Y.iloc[:,11]

In [53]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [54]:
import lazypredict
from lazypredict.Supervised import LazyClassifier

In [55]:
clf = LazyClassifier(verbose=0,ignore_warnings=True)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)
models

100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:15<00:00,  1.92it/s]


Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
LinearDiscriminantAnalysis         0.34               0.23    None      0.27   
LogisticRegression                 0.37               0.23    None      0.29   
RidgeClassifier                    0.37               0.23    None      0.28   
LinearSVC                          0.37               0.22    None      0.28   
RidgeClassifierCV                  0.37               0.22    None      0.27   
CalibratedClassifierCV             0.37               0.22    None      0.28   
NearestCentroid                    0.33               0.22    None      0.24   
GaussianNB                         0.36               0.21    None      0.27   
QuadraticDiscriminantAnalysis      0.35               0.21    None      0.26   
Perceptron                         0.34               0.21    None      0.29   
BaggingClassifier                  0.30               0.21    None      0.25   
PassiveAggressiveClassifier        0.35               0.19    None      0.25   
SGDClassifier                      0.41               0.19    None      0.27   
ExtraTreeClassifier                0.42               0.17    None      0.28   
SVC                                0.41               0.17    None      0.24   
RandomForestClassifier             0.41               0.17    None      0.24   
AdaBoostClassifier                 0.41               0.17    None      0.24   
LabelSpreading                     0.01               0.17    None      0.00   
LabelPropagation                   0.01               0.17    None      0.00   
DecisionTreeClassifier             0.41               0.17    None      0.24   
LGBMClassifier                     0.41               0.17    None      0.24   
XGBClassifier                      0.41               0.17    None      0.24   
BernoulliNB                        0.40               0.16    None      0.28   
DummyClassifier                    0.35               0.16    None      0.35   
KNeighborsClassifier               0.38               0.16    None      0.32   
ExtraTreesClassifier               0.17               0.15    None      0.15   

                               Time Taken  
Model                                      
LinearDiscriminantAnalysis           0.08  
LogisticRegression                   0.32  
RidgeClassifier                      0.07  
LinearSVC                            1.22  
RidgeClassifierCV                    0.05  
CalibratedClassifierCV               5.07  
NearestCentroid                      0.04  
GaussianNB                           0.06  
QuadraticDiscriminantAnalysis        0.07  
Perceptron                           0.07  
BaggingClassifier                    0.30  
PassiveAggressiveClassifier          0.07  
SGDClassifier                        0.10  
ExtraTreeClassifier                  0.04  
SVC                                  0.62  
RandomForestClassifier               1.11  
AdaBoostClassifier                   0.53  
LabelSpreading                       0.60  
LabelPropagation                     0.56  
DecisionTreeClassifier               0.07  
LGBMClassifier                       1.70  
XGBClassifier                        0.99  
BernoulliNB                          0.05  
DummyClassifier                      0.04  
KNeighborsClassifier                 0.36  
ExtraTreesClassifier                 0.86

In [56]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

<IPython.core.display.Javascript object>

In [57]:
print('Evaluation Metrics – Random Forest:')
print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred)))
print('F1 Score: ' + str(metrics.f1_score(y_test, y_pred, average='macro')))

Evaluation Metrics – Random Forest:
Accuracy: 0.4300234558248632
F1 Score: 0.1235516754623514


In [58]:
rf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [59]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(max_features='auto', oob_score=True, random_state=1, n_jobs=-1)

param_grid = { "criterion" : ["gini", "entropy"], "min_samples_leaf" : [1, 5, 10], "min_samples_split" : [2, 4, 10, 12, 16], "n_estimators": [50, 100, 400, 700, 1000]}

gs = GridSearchCV(estimator=rf, param_grid=param_grid, scoring='accuracy', cv=3, n_jobs=-1)

gs = gs.fit(X_train,y_train)

In [60]:
print(gs.best_score_)
print(gs.best_params_)

0.5645457444118261
{'criterion': 'gini', 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 400}


In [61]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(criterion='gini', 
                             n_estimators=400,
                             min_samples_split=10,
                             min_samples_leaf=1,
                             max_features='auto',
                             oob_score=True,
                             random_state=1,
                             n_jobs=-1)
rf.fit(X_train, y_train)
print("%.4f" % rf.oob_score_)

0.6966


In [62]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = rf.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   9   0   0   0]
 [  0   0  45   0   0   0]
 [  0   0 529   0   0   0]
 [  0   0 522   0   0   0]
 [  0   0 161   0   0   0]
 [  0   0  13   0   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         9
           4       0.00      0.00      0.00        45
           5       0.41      1.00      0.59       529
           6       0.00      0.00      0.00       522
           7       0.00      0.00      0.00       161
           8       0.00      0.00      0.00        13

    accuracy                           0.41      1279
   macro avg       0.07      0.17      0.10      1279
weighted avg       0.17      0.41      0.24      1279

0.41360437842064113


In [64]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
model_res = clf.fit(X_train, y_train)

In [65]:
y_pred = clf.predict(X_test)

In [66]:
print('Evaluation Metrics – Random Forest:')
print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred)))
print('F1 Score: ' + str(metrics.f1_score(y_test, y_pred, average='macro')))

Evaluation Metrics – Random Forest:
Accuracy: 0.3721657544956998
F1 Score: 0.150202486390802


In [71]:
# Create first pipeline for base without reducing features.

#pipe = Pipeline([('classifier' , RandomForestClassifier())])
# pipe = Pipeline([('classifier', RandomForestClassifier())])

# Create param grid.
clf = LogisticRegression()

param_grid = {
     'penalty' : ['l1', 'l2'],
    'C' : np.logspace(-4, 4, 20),
    'solver' : ['liblinear', 'newton-cg']
}

# Create grid search object

clf = GridSearchCV(estimator=clf, param_grid = param_grid, cv = 5, verbose=True, n_jobs=-1)

# Fit on data

best_clf = clf.fit(X_train, y_train)

Fitting 5 folds for each of 80 candidates, totalling 400 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    3.2s
[Parallel(n_jobs=-1)]: Done 400 out of 400 | elapsed:    5.8s finished


In [72]:
print(clf.best_score_)
print(clf.best_params_)

0.5910845588235294
{'C': 0.03359818286283781, 'penalty': 'l2', 'solver': 'newton-cg'}


In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier( bootstrap=True,
                             ccp_alpha= 0.0,
                             class_weight= None,
                             criterion= 'gini',
                             max_depth= None,
                             max_features= 'auto',
                             max_leaf_nodes= None,
                             max_samples= None,
                             min_impurity_decrease= 0.0,
                             min_impurity_split= None,
                             min_samples_leaf= 1,
                             min_samples_split= 2,
                             min_weight_fraction_leaf= 0.0,
                             n_estimators= 100,
                             n_jobs= None,
                             oob_score=True,
                             random_state= None,
                             verbose= 0,
                             warm_start = False)
rf.fit(X_train, y_train)
print("%.4f" % rf.oob_score_)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = rf.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, make_scorer
from sklearn.model_selection import cross_val_score
#from sklearn.preprocessing import Imputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline

# Custom scorer for cross validation
scorer = make_scorer(f1_score, greater_is_better=True, average = 'macro')

In [ ]:
cv_score = cross_val_score(rf, X_train, y_train, cv = 4, scoring = scorer)

print(f'10 Fold Cross Validation F1 Score = {round(cv_score.mean(), 4)} with std = {round(cv_score.std(), 4)}')

In [ ]:
cv_score = cross_val_score(rf, X_train, y_train, cv = 4, scoring = scorer)

print(f'10 Fold Cross Validation F1 Score = {round(cv_score.mean(), 4)} with std = {round(cv_score.std(), 4)}')